# Generated by Django 3.2.6 on 2021-08-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210818_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_amount',
        ),
    ]
