# Generated by Django 3.2.6 on 2021-09-09 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_code', models.UUIDField()),
                ('reward_points', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('total_amount', models.FloatField()),
                ('total_wine_purchased', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
