# Generated by Django 3.2.6 on 2021-09-09 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reward_program', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_at', models.DateTimeField(null=True)),
                ('reward_points', models.IntegerField(default=0)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200)),
                ('favorite_region', models.CharField(blank=True, max_length=300)),
                ('favorite_wine_type', models.CharField(blank=True, max_length=200)),
                ('favorite_business', models.ManyToManyField(to='business.Business')),
                ('favorite_wine', models.ManyToManyField(to='wine.Wine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerRewardProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('reward_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward_program.rewardprogram')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='reward_program',
            field=models.ManyToManyField(through='customer.CustomerRewardProgram', to='reward_program.RewardProgram'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
