# Generated by Django 3.2.6 on 2021-09-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('delete_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('lookup_key', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('stripe_product_id', models.CharField(blank=True, max_length=200)),
                ('stripe_price_id', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
