# Generated by Django 3.2.6 on 2021-08-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
                ('role', models.CharField(choices=[('emp', 'Employee'), ('admin', 'Admin')], default='emp', max_length=10)),
            ],
        ),
    ]
