# Generated by Django 3.2.6 on 2021-08-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('emp', 'Employee'), ('admin', 'Admin')], default='emp', max_length=10),
        ),
    ]
