# Generated by Django 3.2.7 on 2021-09-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_program', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='membership',
            new_name='membership_program',
        ),
    ]
