# Generated by Django 3.2.7 on 2021-09-10 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='adress',
            new_name='address',
        ),
    ]
