# Generated by Django 3.2.6 on 2021-08-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='delete_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
