# Generated by Django 3.2.6 on 2021-08-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210818_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateEmailVerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_email', models.EmailField(max_length=254)),
                ('new_email', models.EmailField(max_length=254)),
                ('verify_code', models.UUIDField()),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
    ]
